=== Kayres21/optical-mb-sim-go/files/networks/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Network Schema",
  "type": "object",
  "properties": {
    "alias": { "type": "string" },
    "name": { "type": "string" },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" }
        },
        "required": ["id"]
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "src": { "type": "integer" },
          "dst": { "type": "integer" },
          "length": { "type": "number" }
        },
        "required": ["id", "src", "dst", "length"]
      }
    }
  },
  "required": ["alias", "name", "nodes", "links"]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_65_METRONA.json
{
  "alias": "METRONA",
  "name": "TOP_65_METRONA",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    },
    {
      "id": 22
    },
    {
      "id": 23
    },
    {
      "id": 24
    },
    {
      "id": 25
    },
    {
      "id": 26
    },
    {
      "id": 27
    },
    {
      "id": 28
    },
    {
      "id": 29
    },
    {
      "id": 30
    },
    {
      "id": 31
    },
    {
      "id": 32
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 1,
      "length": 87.57000000000001
    },
    {
      "id": 1,
      "src": 1,
      "dst": 0,
      "length": 87.57000000000001
    },
    {
      "id": 2,
      "src": 0,
      "dst": 4,
      "length": 302.895
    },
    {
      "id": 3,
      "src": 4,
      "dst": 0,
      "length": 302.895
    },
    {
      "id": 4,
      "src": 1,
      "dst": 2,
      "length": 73.725
    },
    {
      "id": 5,
      "src": 2,
      "dst": 1,
      "length": 73.725
    },
    {
      "id": 6,
      "src": 2,
      "dst": 3,
      "length": 90.27
    },
    {
      "id": 7,
      "src": 3,
      "dst": 2,
      "length": 90.27
    },
    {
      "id": 8,
      "src": 3,
      "dst": 8,
      "length": 169.125
    },
    {
      "id": 9,
      "src": 8,
      "dst": 3,
      "length": 169.125
    },
    {
      "id": 10,
      "src": 3,
      "dst": 20,
      "length": 128.97
    },
    {
      "id": 11,
      "src": 20,
      "dst": 3,
      "length": 128.97
    },
    {
      "id": 12,
      "src": 4,
      "dst": 5,
      "length": 133.77
    },
    {
      "id": 13,
      "src": 5,
      "dst": 4,
      "length": 133.77
    },
    {
      "id": 14,
      "src": 5,
      "dst": 11,
      "length": 114.42
    },
    {
      "id": 15,
      "src": 11,
      "dst": 5,
      "length": 114.42
    },
    {
      "id": 16,
      "src": 6,
      "dst": 7,
      "length": 82.785
    },
    {
      "id": 17,
      "src": 7,
      "dst": 6,
      "length": 82.785
    },
    {
      "id": 18,
      "src": 6,
      "dst": 20,
      "length": 201.51
    },
    {
      "id": 19,
      "src": 20,
      "dst": 6,
      "length": 201.51
    },
    {
      "id": 20,
      "src": 7,
      "dst": 20,
      "length": 154.155
    },
    {
      "id": 21,
      "src": 20,
      "dst": 7,
      "length": 154.155
    },
    {
      "id": 22,
      "src": 8,
      "dst": 20,
      "length": 177.87
    },
    {
      "id": 23,
      "src": 20,
      "dst": 8,
      "length": 177.87
    },
    {
      "id": 24,
      "src": 8,
      "dst": 11,
      "length": 87.9
    },
    {
      "id": 25,
      "src": 11,
      "dst": 8,
      "length": 87.9
    },
    {
      "id": 26,
      "src": 9,
      "dst": 11,
      "length": 123.855
    },
    {
      "id": 27,
      "src": 11,
      "dst": 9,
      "length": 123.855
    },
    {
      "id": 28,
      "src": 9,
      "dst": 10,
      "length": 129.6
    },
    {
      "id": 29,
      "src": 10,
      "dst": 9,
      "length": 129.6
    },
    {
      "id": 30,
      "src": 10,
      "dst": 14,
      "length": 155.79
    },
    {
      "id": 31,
      "src": 14,
      "dst": 10,
      "length": 155.79
    },
    {
      "id": 32,
      "src": 11,
      "dst": 12,
      "length": 7392.174999999999
    },
    {
      "id": 33,
      "src": 12,
      "dst": 11,
      "length": 7392.174999999999
    },
    {
      "id": 34,
      "src": 12,
      "dst": 14,
      "length": 7332.212500000001
    },
    {
      "id": 35,
      "src": 14,
      "dst": 12,
      "length": 7332.212500000001
    },
    {
      "id": 36,
      "src": 12,
      "dst": 13,
      "length": 7295.175
    },
    {
      "id": 37,
      "src": 13,
      "dst": 12,
      "length": 7295.175
    },
    {
      "id": 38,
      "src": 13,
      "dst": 15,
      "length": 68.4
    },
    {
      "id": 39,
      "src": 15,
      "dst": 13,
      "length": 68.4
    },
    {
      "id": 40,
      "src": 15,
      "dst": 16,
      "length": 32.55
    },
    {
      "id": 41,
      "src": 16,
      "dst": 15,
      "length": 32.55
    },
    {
      "id": 42,
      "src": 15,
      "dst": 19,
      "length": 41.625
    },
    {
      "id": 43,
      "src": 19,
      "dst": 15,
      "length": 41.625
    },
    {
      "id": 44,
      "src": 16,
      "dst": 17,
      "length": 30.93
    },
    {
      "id": 45,
      "src": 17,
      "dst": 16,
      "length": 30.93
    },
    {
      "id": 46,
      "src": 17,
      "dst": 18,
      "length": 128.7
    },
    {
      "id": 47,
      "src": 18,
      "dst": 17,
      "length": 128.7
    },
    {
      "id": 48,
      "src": 18,
      "dst": 26,
      "length": 69.885
    },
    {
      "id": 49,
      "src": 26,
      "dst": 18,
      "length": 69.885
    },
    {
      "id": 50,
      "src": 19,
      "dst": 20,
      "length": 58.02
    },
    {
      "id": 51,
      "src": 20,
      "dst": 19,
      "length": 58.02
    },
    {
      "id": 52,
      "src": 19,
      "dst": 21,
      "length": 93.795
    },
    {
      "id": 53,
      "src": 21,
      "dst": 19,
      "length": 93.795
    },
    {
      "id": 54,
      "src": 21,
      "dst": 22,
      "length": 77.535
    },
    {
      "id": 55,
      "src": 22,
      "dst": 21,
      "length": 77.535
    },
    {
      "id": 56,
      "src": 22,
      "dst": 23,
      "length": 75.135
    },
    {
      "id": 57,
      "src": 23,
      "dst": 22,
      "length": 75.135
    },
    {
      "id": 58,
      "src": 22,
      "dst": 25,
      "length": 71.685
    },
    {
      "id": 59,
      "src": 25,
      "dst": 22,
      "length": 71.685
    },
    {
      "id": 60,
      "src": 22,
      "dst": 24,
      "length": 64.785
    },
    {
      "id": 61,
      "src": 24,
      "dst": 22,
      "length": 64.785
    },
    {
      "id": 62,
      "src": 23,
      "dst": 24,
      "length": 65.475
    },
    {
      "id": 63,
      "src": 24,
      "dst": 23,
      "length": 65.475
    },
    {
      "id": 64,
      "src": 24,
      "dst": 30,
      "length": 235.695
    },
    {
      "id": 65,
      "src": 30,
      "dst": 24,
      "length": 235.695
    },
    {
      "id": 66,
      "src": 25,
      "dst": 26,
      "length": 20.505
    },
    {
      "id": 67,
      "src": 26,
      "dst": 25,
      "length": 20.505
    },
    {
      "id": 68,
      "src": 25,
      "dst": 27,
      "length": 139.815
    },
    {
      "id": 69,
      "src": 27,
      "dst": 25,
      "length": 139.815
    },
    {
      "id": 70,
      "src": 27,
      "dst": 28,
      "length": 56.835
    },
    {
      "id": 71,
      "src": 28,
      "dst": 27,
      "length": 56.835
    },
    {
      "id": 72,
      "src": 28,
      "dst": 29,
      "length": 24.81
    },
    {
      "id": 73,
      "src": 29,
      "dst": 28,
      "length": 24.81
    },
    {
      "id": 74,
      "src": 29,
      "dst": 30,
      "length": 191.655
    },
    {
      "id": 75,
      "src": 30,
      "dst": 29,
      "length": 191.655
    },
    {
      "id": 76,
      "src": 29,
      "dst": 31,
      "length": 221.07
    },
    {
      "id": 77,
      "src": 31,
      "dst": 29,
      "length": 221.07
    },
    {
      "id": 78,
      "src": 31,
      "dst": 32,
      "length": 100.455
    },
    {
      "id": 79,
      "src": 32,
      "dst": 31,
      "length": 100.455
    },
    {
      "id": 80,
      "src": 32,
      "dst": 30,
      "length": 145.275
    },
    {
      "id": 81,
      "src": 30,
      "dst": 32,
      "length": 145.275
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_27_DT17.json
{
  "alias": "DT17",
  "name": "TOP_27_DT17",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 6,
      "length": 306.3
    },
    {
      "id": 1,
      "src": 6,
      "dst": 0,
      "length": 306.3
    },
    {
      "id": 2,
      "src": 0,
      "dst": 7,
      "length": 160.9
    },
    {
      "id": 3,
      "src": 7,
      "dst": 0,
      "length": 160.9
    },
    {
      "id": 4,
      "src": 0,
      "dst": 9,
      "length": 173.3
    },
    {
      "id": 5,
      "src": 9,
      "dst": 0,
      "length": 173.3
    },
    {
      "id": 6,
      "src": 1,
      "dst": 6,
      "length": 114.7
    },
    {
      "id": 7,
      "src": 6,
      "dst": 1,
      "length": 114.7
    },
    {
      "id": 8,
      "src": 1,
      "dst": 7,
      "length": 121.3
    },
    {
      "id": 9,
      "src": 7,
      "dst": 1,
      "length": 121.3
    },
    {
      "id": 10,
      "src": 1,
      "dst": 4,
      "length": 278.5
    },
    {
      "id": 11,
      "src": 4,
      "dst": 1,
      "length": 278.5
    },
    {
      "id": 12,
      "src": 2,
      "dst": 4,
      "length": 37.4
    },
    {
      "id": 13,
      "src": 4,
      "dst": 2,
      "length": 37.4
    },
    {
      "id": 14,
      "src": 2,
      "dst": 7,
      "length": 230.4
    },
    {
      "id": 15,
      "src": 7,
      "dst": 2,
      "length": 230.4
    },
    {
      "id": 16,
      "src": 2,
      "dst": 8,
      "length": 84.3
    },
    {
      "id": 17,
      "src": 8,
      "dst": 2,
      "length": 84.3
    },
    {
      "id": 18,
      "src": 3,
      "dst": 4,
      "length": 36.9
    },
    {
      "id": 19,
      "src": 4,
      "dst": 3,
      "length": 36.9
    },
    {
      "id": 20,
      "src": 3,
      "dst": 8,
      "length": 40.9
    },
    {
      "id": 21,
      "src": 8,
      "dst": 3,
      "length": 40.9
    },
    {
      "id": 22,
      "src": 5,
      "dst": 7,
      "length": 313.9
    },
    {
      "id": 23,
      "src": 7,
      "dst": 5,
      "length": 313.9
    },
    {
      "id": 24,
      "src": 5,
      "dst": 8,
      "length": 182.0
    },
    {
      "id": 25,
      "src": 8,
      "dst": 5,
      "length": 182.0
    },
    {
      "id": 26,
      "src": 5,
      "dst": 9,
      "length": 352.6
    },
    {
      "id": 27,
      "src": 9,
      "dst": 5,
      "length": 352.6
    },
    {
      "id": 28,
      "src": 5,
      "dst": 12,
      "length": 207.4
    },
    {
      "id": 29,
      "src": 12,
      "dst": 5,
      "length": 207.4
    },
    {
      "id": 30,
      "src": 5,
      "dst": 11,
      "length": 224.1
    },
    {
      "id": 31,
      "src": 11,
      "dst": 5,
      "length": 224.1
    },
    {
      "id": 32,
      "src": 7,
      "dst": 9,
      "length": 257.2
    },
    {
      "id": 33,
      "src": 9,
      "dst": 7,
      "length": 257.2
    },
    {
      "id": 34,
      "src": 9,
      "dst": 11,
      "length": 274.4
    },
    {
      "id": 35,
      "src": 11,
      "dst": 9,
      "length": 274.4
    },
    {
      "id": 36,
      "src": 10,
      "dst": 11,
      "length": 180.8
    },
    {
      "id": 37,
      "src": 11,
      "dst": 10,
      "length": 180.8
    },
    {
      "id": 38,
      "src": 10,
      "dst": 13,
      "length": 145.6
    },
    {
      "id": 39,
      "src": 13,
      "dst": 10,
      "length": 145.6
    },
    {
      "id": 40,
      "src": 11,
      "dst": 12,
      "length": 188.7
    },
    {
      "id": 41,
      "src": 12,
      "dst": 11,
      "length": 188.7
    },
    {
      "id": 42,
      "src": 12,
      "dst": 13,
      "length": 37.1
    },
    {
      "id": 43,
      "src": 13,
      "dst": 12,
      "length": 37.1
    },
    {
      "id": 44,
      "src": 0,
      "dst": 7,
      "length": 294.9
    },
    {
      "id": 45,
      "src": 7,
      "dst": 0,
      "length": 294.9
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_89_RENATER1999.json
{
  "alias": "RENATER1999",
  "name": "TOP_89_RENATER1999",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    },
    {
      "id": 22
    },
    {
      "id": 23
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 15,
      "length": 310.1353076025006
    },
    {
      "id": 1,
      "src": 15,
      "dst": 0,
      "length": 310.1353076025006
    },
    {
      "id": 2,
      "src": 1,
      "dst": 11,
      "length": 881.9148496472068
    },
    {
      "id": 3,
      "src": 11,
      "dst": 1,
      "length": 881.9148496472068
    },
    {
      "id": 4,
      "src": 1,
      "dst": 6,
      "length": 294.7081152484741
    },
    {
      "id": 5,
      "src": 6,
      "dst": 1,
      "length": 294.7081152484741
    },
    {
      "id": 6,
      "src": 2,
      "dst": 11,
      "length": 162.9284693466608
    },
    {
      "id": 7,
      "src": 11,
      "dst": 2,
      "length": 162.9284693466608
    },
    {
      "id": 8,
      "src": 2,
      "dst": 15,
      "length": 285.5552568765627
    },
    {
      "id": 9,
      "src": 15,
      "dst": 2,
      "length": 285.5552568765627
    },
    {
      "id": 10,
      "src": 3,
      "dst": 15,
      "length": 164.8408021406742
    },
    {
      "id": 11,
      "src": 15,
      "dst": 3,
      "length": 164.8408021406742
    },
    {
      "id": 12,
      "src": 4,
      "dst": 11,
      "length": 391.9101437019439
    },
    {
      "id": 13,
      "src": 11,
      "dst": 4,
      "length": 391.9101437019439
    },
    {
      "id": 14,
      "src": 4,
      "dst": 5,
      "length": 114.8694624115643
    },
    {
      "id": 15,
      "src": 5,
      "dst": 4,
      "length": 114.8694624115643
    },
    {
      "id": 16,
      "src": 7,
      "dst": 10,
      "length": 206.0046605848057
    },
    {
      "id": 17,
      "src": 10,
      "dst": 7,
      "length": 206.0046605848057
    },
    {
      "id": 18,
      "src": 8,
      "dst": 10,
      "length": 140.4186699208927
    },
    {
      "id": 19,
      "src": 10,
      "dst": 8,
      "length": 140.4186699208927
    },
    {
      "id": 20,
      "src": 9,
      "dst": 12,
      "length": 327.2726517839708
    },
    {
      "id": 21,
      "src": 12,
      "dst": 9,
      "length": 327.2726517839708
    },
    {
      "id": 22,
      "src": 9,
      "dst": 13,
      "length": 235.8713173227889
    },
    {
      "id": 23,
      "src": 13,
      "dst": 9,
      "length": 235.8713173227889
    },
    {
      "id": 24,
      "src": 10,
      "dst": 11,
      "length": 589.2508599924295
    },
    {
      "id": 25,
      "src": 11,
      "dst": 10,
      "length": 589.2508599924295
    },
    {
      "id": 26,
      "src": 10,
      "dst": 13,
      "length": 413.8389675135418
    },
    {
      "id": 27,
      "src": 13,
      "dst": 10,
      "length": 413.8389675135418
    },
    {
      "id": 28,
      "src": 11,
      "dst": 17,
      "length": 424.175933883086
    },
    {
      "id": 29,
      "src": 17,
      "dst": 11,
      "length": 424.175933883086
    },
    {
      "id": 30,
      "src": 11,
      "dst": 18,
      "length": 195.388303552465
    },
    {
      "id": 31,
      "src": 18,
      "dst": 11,
      "length": 195.388303552465
    },
    {
      "id": 32,
      "src": 11,
      "dst": 19,
      "length": 108.5465409911054
    },
    {
      "id": 33,
      "src": 19,
      "dst": 11,
      "length": 108.5465409911054
    },
    {
      "id": 34,
      "src": 11,
      "dst": 20,
      "length": 306.8625058255422
    },
    {
      "id": 35,
      "src": 20,
      "dst": 11,
      "length": 306.8625058255422
    },
    {
      "id": 36,
      "src": 11,
      "dst": 21,
      "length": 168.1761860997829
    },
    {
      "id": 37,
      "src": 21,
      "dst": 11,
      "length": 168.1761860997829
    },
    {
      "id": 38,
      "src": 11,
      "dst": 23,
      "length": 463.7727051434647
    },
    {
      "id": 39,
      "src": 23,
      "dst": 11,
      "length": 463.7727051434647
    },
    {
      "id": 40,
      "src": 14,
      "dst": 23,
      "length": 144.1831991731319
    },
    {
      "id": 41,
      "src": 23,
      "dst": 14,
      "length": 144.1831991731319
    },
    {
      "id": 42,
      "src": 16,
      "dst": 17,
      "length": 171.6753296158936
    },
    {
      "id": 43,
      "src": 17,
      "dst": 16,
      "length": 171.6753296158936
    },
    {
      "id": 44,
      "src": 21,
      "dst": 22,
      "length": 164.130662797804
    },
    {
      "id": 45,
      "src": 22,
      "dst": 21,
      "length": 164.130662797804
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_35_GEANT.json
{
  "alias": "GEANT",
  "name": "TOP_35_GEANT",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 2,
      "length": 1205.741718697376
    },
    {
      "id": 1,
      "src": 2,
      "dst": 0,
      "length": 1205.741718697376
    },
    {
      "id": 2,
      "src": 0,
      "dst": 4,
      "length": 896.1689368748143
    },
    {
      "id": 3,
      "src": 4,
      "dst": 0,
      "length": 896.1689368748143
    },
    {
      "id": 4,
      "src": 0,
      "dst": 9,
      "length": 326.792609366545
    },
    {
      "id": 5,
      "src": 9,
      "dst": 0,
      "length": 326.792609366545
    },
    {
      "id": 6,
      "src": 0,
      "dst": 15,
      "length": 8494.167120778287
    },
    {
      "id": 7,
      "src": 15,
      "dst": 0,
      "length": 8494.167120778287
    },
    {
      "id": 8,
      "src": 0,
      "dst": 19,
      "length": 416.2042271506733
    },
    {
      "id": 9,
      "src": 19,
      "dst": 0,
      "length": 416.2042271506733
    },
    {
      "id": 10,
      "src": 1,
      "dst": 6,
      "length": 395.5671921820349
    },
    {
      "id": 11,
      "src": 6,
      "dst": 1,
      "length": 395.5671921820349
    },
    {
      "id": 12,
      "src": 1,
      "dst": 13,
      "length": 280.095250485013
    },
    {
      "id": 13,
      "src": 13,
      "dst": 1,
      "length": 280.095250485013
    },
    {
      "id": 14,
      "src": 1,
      "dst": 14,
      "length": 253.748818411639
    },
    {
      "id": 15,
      "src": 14,
      "dst": 1,
      "length": 253.748818411639
    },
    {
      "id": 16,
      "src": 2,
      "dst": 6,
      "length": 614.5443962857513
    },
    {
      "id": 17,
      "src": 6,
      "dst": 2,
      "length": 614.5443962857513
    },
    {
      "id": 18,
      "src": 2,
      "dst": 12,
      "length": 375.2774972722834
    },
    {
      "id": 19,
      "src": 12,
      "dst": 2,
      "length": 375.2774972722834
    },
    {
      "id": 20,
      "src": 3,
      "dst": 4,
      "length": 615.985650719161
    },
    {
      "id": 21,
      "src": 4,
      "dst": 3,
      "length": 615.985650719161
    },
    {
      "id": 22,
      "src": 3,
      "dst": 16,
      "length": 463.2422772840073
    },
    {
      "id": 23,
      "src": 16,
      "dst": 3,
      "length": 463.2422772840073
    },
    {
      "id": 24,
      "src": 3,
      "dst": 20,
      "length": 434.9231408588021
    },
    {
      "id": 25,
      "src": 20,
      "dst": 3,
      "length": 434.9231408588021
    },
    {
      "id": 26,
      "src": 4,
      "dst": 6,
      "length": 717.2335947676761
    },
    {
      "id": 27,
      "src": 6,
      "dst": 4,
      "length": 717.2335947676761
    },
    {
      "id": 28,
      "src": 4,
      "dst": 7,
      "length": 2240.980605010167
    },
    {
      "id": 29,
      "src": 7,
      "dst": 4,
      "length": 2240.980605010167
    },
    {
      "id": 30,
      "src": 4,
      "dst": 10,
      "length": 1500.0
    },
    {
      "id": 31,
      "src": 10,
      "dst": 4,
      "length": 1500.0
    },
    {
      "id": 32,
      "src": 4,
      "dst": 12,
      "length": 777.315099448178
    },
    {
      "id": 33,
      "src": 12,
      "dst": 4,
      "length": 777.315099448178
    },
    {
      "id": 34,
      "src": 4,
      "dst": 14,
      "length": 537.4556978209507
    },
    {
      "id": 35,
      "src": 14,
      "dst": 4,
      "length": 537.4556978209507
    },
    {
      "id": 36,
      "src": 4,
      "dst": 18,
      "length": 1500.0
    },
    {
      "id": 37,
      "src": 18,
      "dst": 4,
      "length": 1500.0
    },
    {
      "id": 38,
      "src": 5,
      "dst": 6,
      "length": 1500.0
    },
    {
      "id": 39,
      "src": 6,
      "dst": 5,
      "length": 1500.0
    },
    {
      "id": 40,
      "src": 5,
      "dst": 12,
      "length": 1500.0
    },
    {
      "id": 41,
      "src": 12,
      "dst": 5,
      "length": 1500.0
    },
    {
      "id": 42,
      "src": 5,
      "dst": 17,
      "length": 754.3780747471078
    },
    {
      "id": 43,
      "src": 17,
      "dst": 5,
      "length": 754.3780747471078
    },
    {
      "id": 44,
      "src": 6,
      "dst": 13,
      "length": 430.2917638658975
    },
    {
      "id": 45,
      "src": 13,
      "dst": 6,
      "length": 430.2917638658975
    },
    {
      "id": 46,
      "src": 6,
      "dst": 21,
      "length": 515.36158679831
    },
    {
      "id": 47,
      "src": 21,
      "dst": 6,
      "length": 515.36158679831
    },
    {
      "id": 48,
      "src": 7,
      "dst": 12,
      "length": 1815.420595779476
    },
    {
      "id": 49,
      "src": 12,
      "dst": 7,
      "length": 1815.420595779476
    },
    {
      "id": 50,
      "src": 8,
      "dst": 9,
      "length": 455.8481192958354
    },
    {
      "id": 51,
      "src": 9,
      "dst": 8,
      "length": 455.8481192958354
    },
    {
      "id": 52,
      "src": 8,
      "dst": 19,
      "length": 173.2635674625123
    },
    {
      "id": 53,
      "src": 19,
      "dst": 8,
      "length": 173.2635674625123
    },
    {
      "id": 54,
      "src": 9,
      "dst": 20,
      "length": 245.5911295353906
    },
    {
      "id": 55,
      "src": 20,
      "dst": 9,
      "length": 245.5911295353906
    },
    {
      "id": 56,
      "src": 10,
      "dst": 21,
      "length": 694.1747825761532
    },
    {
      "id": 57,
      "src": 21,
      "dst": 10,
      "length": 694.1747825761532
    },
    {
      "id": 58,
      "src": 11,
      "dst": 12,
      "length": 3319.590434051195
    },
    {
      "id": 59,
      "src": 12,
      "dst": 11,
      "length": 3319.590434051195
    },
    {
      "id": 60,
      "src": 11,
      "dst": 14,
      "length": 4116.059850695134
    },
    {
      "id": 61,
      "src": 14,
      "dst": 11,
      "length": 4116.059850695134
    },
    {
      "id": 62,
      "src": 14,
      "dst": 21,
      "length": 538.6083143873095
    },
    {
      "id": 63,
      "src": 21,
      "dst": 14,
      "length": 538.6083143873095
    },
    {
      "id": 64,
      "src": 15,
      "dst": 21,
      "length": 6961.479107534074
    },
    {
      "id": 65,
      "src": 21,
      "dst": 15,
      "length": 6961.479107534074
    },
    {
      "id": 66,
      "src": 16,
      "dst": 18,
      "length": 1165.404461338919
    },
    {
      "id": 67,
      "src": 18,
      "dst": 16,
      "length": 1165.404461338919
    },
    {
      "id": 68,
      "src": 17,
      "dst": 21,
      "length": 1983.225004686776
    },
    {
      "id": 69,
      "src": 21,
      "dst": 17,
      "length": 1983.225004686776
    },
    {
      "id": 70,
      "src": 18,
      "dst": 21,
      "length": 1781.016899491856
    },
    {
      "id": 71,
      "src": 21,
      "dst": 18,
      "length": 1781.016899491856
    }
  ]
}
