=== Kayres21/optical-mb-sim-go/files/networks/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Network Schema",
  "type": "object",
  "properties": {
    "alias": { "type": "string" },
    "name": { "type": "string" },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" }
        },
        "required": ["id"]
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "src": { "type": "integer" },
          "dst": { "type": "integer" },
          "length": { "type": "number" }
        },
        "required": ["id", "src", "dst", "length"]
      }
    }
  },
  "required": ["alias", "name", "nodes", "links"]
}

=== Kayres21/optical-mb-sim-go/files/networks/EON.json
{
    "alias": "BDM_EON",
    "nodes": [
        {
            "id": 0
        },
        {
            "id": 1
        },
        {
            "id": 2
        },
        {
            "id": 3
        },
        {
            "id": 4
        },
        {
            "id": 5
        },
        {
            "id": 6
        },
        {
            "id": 7
        },
        {
            "id": 8
        },
        {
            "id": 9
        },
        {
            "id": 10
        },
        {
            "id": 11
        },
        {
            "id": 12
        },
        {
            "id": 13
        },
        {
            "id": 14
        },
        {
            "id": 15
        },
        {
            "id": 16
        },
        {
            "id": 17
        },
        {
            "id": 18
        },
        {
            "id": 19
        }
    ],
    "links": [
        {
            "dst": 0,
            "id": 0,
            "length": 503,
            "src": 1
        },
        {
            "dst": 1,
            "id": 1,
            "length": 503,
            "src": 0
        },
        {
            "dst": 0,
            "id": 2,
            "length": 1574,
            "src": 4
        },
        {
            "dst": 4,
            "id": 3,
            "length": 1574,
            "src": 0
        },
        {
            "dst": 1,
            "id": 4,
            "length": 1053,
            "src": 3
        },
        {
            "dst": 3,
            "id": 5,
            "length": 1053,
            "src": 1
        },
        {
            "dst": 2,
            "id": 6,
            "length": 777,
            "src": 3
        },
        {
            "dst": 3,
            "id": 7,
            "length": 777,
            "src": 2
        },
        {
            "dst": 2,
            "id": 8,
            "length": 463,
            "src": 4
        },
        {
            "dst": 4,
            "id": 9,
            "length": 463,
            "src": 2
        },
        {
            "dst": 3,
            "id": 10,
            "length": 341,
            "src": 4
        },
        {
            "dst": 4,
            "id": 11,
            "length": 341,
            "src": 3
        },
        {
            "dst": 3,
            "id": 12,
            "length": 261,
            "src": 5
        },
        {
            "dst": 5,
            "id": 13,
            "length": 261,
            "src": 3
        },
        {
            "dst": 3,
            "id": 14,
            "length": 641,
            "src": 8
        },
        {
            "dst": 8,
            "id": 15,
            "length": 641,
            "src": 3
        },
        {
            "dst": 3,
            "id": 16,
            "length": 557,
            "src": 9
        },
        {
            "dst": 9,
            "id": 17,
            "length": 557,
            "src": 3
        },
        {
            "dst": 4,
            "id": 18,
            "length": 328,
            "src": 5
        },
        {
            "dst": 5,
            "id": 19,
            "length": 328,
            "src": 4
        },
        {
            "dst": 4,
            "id": 20,
            "length": 494,
            "src": 6
        },
        {
            "dst": 6,
            "id": 21,
            "length": 494,
            "src": 4
        },
        {
            "dst": 4,
            "id": 22,
            "length": 1165,
            "src": 13
        },
        {
            "dst": 13,
            "id": 23,
            "length": 1165,
            "src": 4
        },
        {
            "dst": 4,
            "id": 24,
            "length": 1059,
            "src": 14
        },
        {
            "dst": 14,
            "id": 25,
            "length": 1059,
            "src": 4
        },
        {
            "dst": 5,
            "id": 26,
            "length": 209,
            "src": 6
        },
        {
            "dst": 6,
            "id": 27,
            "length": 209,
            "src": 5
        },
        {
            "dst": 5,
            "id": 28,
            "length": 233,
            "src": 7
        },
        {
            "dst": 7,
            "id": 29,
            "length": 233,
            "src": 5
        },
        {
            "dst": 5,
            "id": 30,
            "length": 641,
            "src": 9
        },
        {
            "dst": 9,
            "id": 31,
            "length": 641,
            "src": 5
        },
        {
            "dst": 6,
            "id": 32,
            "length": 371,
            "src": 7
        },
        {
            "dst": 7,
            "id": 33,
            "length": 371,
            "src": 6
        },
        {
            "dst": 6,
            "id": 34,
            "length": 973,
            "src": 11
        },
        {
            "dst": 11,
            "id": 35,
            "length": 973,
            "src": 6
        },
        {
            "dst": 6,
            "id": 36,
            "length": 904,
            "src": 12
        },
        {
            "dst": 12,
            "id": 37,
            "length": 904,
            "src": 6
        },
        {
            "dst": 6,
            "id": 38,
            "length": 648,
            "src": 14
        },
        {
            "dst": 14,
            "id": 39,
            "length": 648,
            "src": 6
        },
        {
            "dst": 8,
            "id": 40,
            "length": 305,
            "src": 9
        },
        {
            "dst": 9,
            "id": 41,
            "length": 305,
            "src": 8
        },
        {
            "dst": 8,
            "id": 42,
            "length": 681,
            "src": 10
        },
        {
            "dst": 10,
            "id": 43,
            "length": 681,
            "src": 8
        },
        {
            "dst": 8,
            "id": 44,
            "length": 876,
            "src": 11
        },
        {
            "dst": 11,
            "id": 45,
            "length": 876,
            "src": 8
        },
        {
            "dst": 8,
            "id": 46,
            "length": 1168,
            "src": 14
        },
        {
            "dst": 14,
            "id": 47,
            "length": 1168,
            "src": 8
        },
        {
            "dst": 8,
            "id": 48,
            "length": 529,
            "src": 16
        },
        {
            "dst": 16,
            "id": 49,
            "length": 529,
            "src": 8
        },
        {
            "dst": 9,
            "id": 50,
            "length": 676,
            "src": 11
        },
        {
            "dst": 11,
            "id": 51,
            "length": 676,
            "src": 9
        },
        {
            "dst": 10,
            "id": 52,
            "length": 517,
            "src": 16
        },
        {
            "dst": 16,
            "id": 53,
            "length": 517,
            "src": 10
        },
        {
            "dst": 10,
            "id": 54,
            "length": 2551,
            "src": 18
        },
        {
            "dst": 18,
            "id": 55,
            "length": 2551,
            "src": 10
        },
        {
            "dst": 11,
            "id": 56,
            "length": 354,
            "src": 14
        },
        {
            "dst": 14,
            "id": 57,
            "length": 354,
            "src": 11
        },
        {
            "dst": 11,
            "id": 58,
            "length": 312,
            "src": 15
        },
        {
            "dst": 15,
            "id": 59,
            "length": 312,
            "src": 11
        },
        {
            "dst": 12,
            "id": 60,
            "length": 485,
            "src": 13
        },
        {
            "dst": 13,
            "id": 61,
            "length": 485,
            "src": 12
        },
        {
            "dst": 12,
            "id": 62,
            "length": 522,
            "src": 17
        },
        {
            "dst": 17,
            "id": 63,
            "length": 522,
            "src": 12
        },
        {
            "dst": 13,
            "id": 64,
            "length": 417,
            "src": 17
        },
        {
            "dst": 17,
            "id": 65,
            "length": 417,
            "src": 13
        },
        {
            "dst": 14,
            "id": 66,
            "length": 666,
            "src": 15
        },
        {
            "dst": 15,
            "id": 67,
            "length": 666,
            "src": 14
        },
        {
            "dst": 14,
            "id": 68,
            "length": 810,
            "src": 17
        },
        {
            "dst": 17,
            "id": 69,
            "length": 810,
            "src": 14
        },
        {
            "dst": 14,
            "id": 70,
            "length": 1608,
            "src": 19
        },
        {
            "dst": 19,
            "id": 71,
            "length": 1608,
            "src": 14
        },
        {
            "dst": 15,
            "id": 72,
            "length": 269,
            "src": 16
        },
        {
            "dst": 16,
            "id": 73,
            "length": 269,
            "src": 15
        },
        {
            "dst": 16,
            "id": 74,
            "length": 1081,
            "src": 18
        },
        {
            "dst": 18,
            "id": 75,
            "length": 1081,
            "src": 16
        },
        {
            "dst": 17,
            "id": 76,
            "length": 1227,
            "src": 19
        },
        {
            "dst": 19,
            "id": 77,
            "length": 1227,
            "src": 17
        }
    ],
    "name": "BDM_EON"
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_52_ISTAR.json
{
  "alias": "ISTAR",
  "name": "TOP_52_ISTAR",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 1,
      "length": 350.1389724135474
    },
    {
      "id": 1,
      "src": 1,
      "dst": 0,
      "length": 350.1389724135474
    },
    {
      "id": 2,
      "src": 0,
      "dst": 3,
      "length": 1026.361517307967
    },
    {
      "id": 3,
      "src": 3,
      "dst": 0,
      "length": 1026.361517307967
    },
    {
      "id": 4,
      "src": 0,
      "dst": 10,
      "length": 755.0357670265992
    },
    {
      "id": 5,
      "src": 10,
      "dst": 0,
      "length": 755.0357670265992
    },
    {
      "id": 6,
      "src": 0,
      "dst": 5,
      "length": 198.5751791544305
    },
    {
      "id": 7,
      "src": 5,
      "dst": 0,
      "length": 198.5751791544305
    },
    {
      "id": 8,
      "src": 0,
      "dst": 17,
      "length": 247.4032001412376
    },
    {
      "id": 9,
      "src": 17,
      "dst": 0,
      "length": 247.4032001412376
    },
    {
      "id": 10,
      "src": 2,
      "dst": 10,
      "length": 250.2531794080375
    },
    {
      "id": 11,
      "src": 10,
      "dst": 2,
      "length": 250.2531794080375
    },
    {
      "id": 12,
      "src": 3,
      "dst": 4,
      "length": 284.3799353856231
    },
    {
      "id": 13,
      "src": 4,
      "dst": 3,
      "length": 284.3799353856231
    },
    {
      "id": 14,
      "src": 3,
      "dst": 6,
      "length": 204.9111545304429
    },
    {
      "id": 15,
      "src": 6,
      "dst": 3,
      "length": 204.9111545304429
    },
    {
      "id": 16,
      "src": 4,
      "dst": 7,
      "length": 468.3506272246442
    },
    {
      "id": 17,
      "src": 7,
      "dst": 4,
      "length": 468.3506272246442
    },
    {
      "id": 18,
      "src": 4,
      "dst": 8,
      "length": 333.9767249411377
    },
    {
      "id": 19,
      "src": 8,
      "dst": 4,
      "length": 333.9767249411377
    },
    {
      "id": 20,
      "src": 9,
      "dst": 12,
      "length": 139.4958300540092
    },
    {
      "id": 21,
      "src": 12,
      "dst": 9,
      "length": 139.4958300540092
    },
    {
      "id": 22,
      "src": 10,
      "dst": 11,
      "length": 101.3005820479409
    },
    {
      "id": 23,
      "src": 11,
      "dst": 10,
      "length": 101.3005820479409
    },
    {
      "id": 24,
      "src": 10,
      "dst": 17,
      "length": 526.0580396293944
    },
    {
      "id": 25,
      "src": 17,
      "dst": 10,
      "length": 526.0580396293944
    },
    {
      "id": 26,
      "src": 10,
      "dst": 18,
      "length": 134.7019718699122
    },
    {
      "id": 27,
      "src": 18,
      "dst": 10,
      "length": 134.7019718699122
    },
    {
      "id": 28,
      "src": 12,
      "dst": 13,
      "length": 1009.95690485004
    },
    {
      "id": 29,
      "src": 13,
      "dst": 12,
      "length": 1009.95690485004
    },
    {
      "id": 30,
      "src": 12,
      "dst": 17,
      "length": 4424.968959600237
    },
    {
      "id": 31,
      "src": 17,
      "dst": 12,
      "length": 4424.968959600237
    },
    {
      "id": 32,
      "src": 13,
      "dst": 14,
      "length": 421.7445112294374
    },
    {
      "id": 33,
      "src": 14,
      "dst": 13,
      "length": 421.7445112294374
    },
    {
      "id": 34,
      "src": 13,
      "dst": 15,
      "length": 262.5774509897452
    },
    {
      "id": 35,
      "src": 15,
      "dst": 13,
      "length": 262.5774509897452
    },
    {
      "id": 36,
      "src": 16,
      "dst": 17,
      "length": 2094.139590166251
    },
    {
      "id": 37,
      "src": 17,
      "dst": 16,
      "length": 2094.139590166251
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_100_SPIRALIGHT.json
{
  "alias": "SPIRALIGHT",
  "name": "TOP_100_SPIRALIGHT",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 3,
      "length": 39.33857400442843
    },
    {
      "id": 1,
      "src": 3,
      "dst": 0,
      "length": 39.33857400442843
    },
    {
      "id": 2,
      "src": 0,
      "dst": 4,
      "length": 75.860016937924
    },
    {
      "id": 3,
      "src": 4,
      "dst": 0,
      "length": 75.860016937924
    },
    {
      "id": 4,
      "src": 1,
      "dst": 2,
      "length": 68.9249489242323
    },
    {
      "id": 5,
      "src": 2,
      "dst": 1,
      "length": 68.9249489242323
    },
    {
      "id": 6,
      "src": 1,
      "dst": 4,
      "length": 165.2065935025056
    },
    {
      "id": 7,
      "src": 4,
      "dst": 1,
      "length": 165.2065935025056
    },
    {
      "id": 8,
      "src": 2,
      "dst": 5,
      "length": 79.92983480781709
    },
    {
      "id": 9,
      "src": 5,
      "dst": 2,
      "length": 79.92983480781709
    },
    {
      "id": 10,
      "src": 3,
      "dst": 5,
      "length": 142.9780858880039
    },
    {
      "id": 11,
      "src": 5,
      "dst": 3,
      "length": 142.9780858880039
    },
    {
      "id": 12,
      "src": 5,
      "dst": 6,
      "length": 176.5788615413109
    },
    {
      "id": 13,
      "src": 6,
      "dst": 5,
      "length": 176.5788615413109
    },
    {
      "id": 14,
      "src": 5,
      "dst": 14,
      "length": 94.11399976081071
    },
    {
      "id": 15,
      "src": 14,
      "dst": 5,
      "length": 94.11399976081071
    },
    {
      "id": 16,
      "src": 6,
      "dst": 8,
      "length": 208.6732898997296
    },
    {
      "id": 17,
      "src": 8,
      "dst": 6,
      "length": 208.6732898997296
    },
    {
      "id": 18,
      "src": 7,
      "dst": 8,
      "length": 209.8743549933172
    },
    {
      "id": 19,
      "src": 8,
      "dst": 7,
      "length": 209.8743549933172
    },
    {
      "id": 20,
      "src": 7,
      "dst": 9,
      "length": 428.3236075781989
    },
    {
      "id": 21,
      "src": 9,
      "dst": 7,
      "length": 428.3236075781989
    },
    {
      "id": 22,
      "src": 9,
      "dst": 10,
      "length": 204.3696485906607
    },
    {
      "id": 23,
      "src": 10,
      "dst": 9,
      "length": 204.3696485906607
    },
    {
      "id": 24,
      "src": 10,
      "dst": 11,
      "length": 64.44807162855902
    },
    {
      "id": 25,
      "src": 11,
      "dst": 10,
      "length": 64.44807162855902
    },
    {
      "id": 26,
      "src": 11,
      "dst": 12,
      "length": 42.52913763533532
    },
    {
      "id": 27,
      "src": 12,
      "dst": 11,
      "length": 42.52913763533532
    },
    {
      "id": 28,
      "src": 12,
      "dst": 13,
      "length": 43.39577057780664
    },
    {
      "id": 29,
      "src": 13,
      "dst": 12,
      "length": 43.39577057780664
    },
    {
      "id": 30,
      "src": 13,
      "dst": 14,
      "length": 70.75718093948329
    },
    {
      "id": 31,
      "src": 14,
      "dst": 13,
      "length": 70.75718093948329
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_47_HIBERNIAUS.json
{
  "alias": "HIBERNIAUS",
  "name": "TOP_47_HIBERNIAUS",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 3,
      "length": 397.6649920225643
    },
    {
      "id": 1,
      "src": 3,
      "dst": 0,
      "length": 397.6649920225643
    },
    {
      "id": 2,
      "src": 0,
      "dst": 12,
      "length": 988.8431894766425
    },
    {
      "id": 3,
      "src": 12,
      "dst": 0,
      "length": 988.8431894766425
    },
    {
      "id": 4,
      "src": 0,
      "dst": 13,
      "length": 277.6478760498783
    },
    {
      "id": 5,
      "src": 13,
      "dst": 0,
      "length": 277.6478760498783
    },
    {
      "id": 6,
      "src": 1,
      "dst": 9,
      "length": 193.5165266446945
    },
    {
      "id": 7,
      "src": 9,
      "dst": 1,
      "length": 193.5165266446945
    },
    {
      "id": 8,
      "src": 1,
      "dst": 2,
      "length": 182.2082908548479
    },
    {
      "id": 9,
      "src": 2,
      "dst": 1,
      "length": 182.2082908548479
    },
    {
      "id": 10,
      "src": 1,
      "dst": 3,
      "length": 336.1009376453503
    },
    {
      "id": 11,
      "src": 3,
      "dst": 1,
      "length": 336.1009376453503
    },
    {
      "id": 12,
      "src": 2,
      "dst": 3,
      "length": 510.74493402578
    },
    {
      "id": 13,
      "src": 3,
      "dst": 2,
      "length": 510.74493402578
    },
    {
      "id": 14,
      "src": 2,
      "dst": 10,
      "length": 70.79952412600834
    },
    {
      "id": 15,
      "src": 10,
      "dst": 2,
      "length": 70.79952412600834
    },
    {
      "id": 16,
      "src": 2,
      "dst": 9,
      "length": 20.83436718327859
    },
    {
      "id": 17,
      "src": 9,
      "dst": 2,
      "length": 20.83436718327859
    },
    {
      "id": 18,
      "src": 3,
      "dst": 6,
      "length": 44.18098870812758
    },
    {
      "id": 19,
      "src": 6,
      "dst": 3,
      "length": 44.18098870812758
    },
    {
      "id": 20,
      "src": 4,
      "dst": 5,
      "length": 312.0079821457963
    },
    {
      "id": 21,
      "src": 5,
      "dst": 4,
      "length": 312.0079821457963
    },
    {
      "id": 22,
      "src": 4,
      "dst": 7,
      "length": 336.2521540699969
    },
    {
      "id": 23,
      "src": 7,
      "dst": 4,
      "length": 336.2521540699969
    },
    {
      "id": 24,
      "src": 5,
      "dst": 8,
      "length": 546.8613702582421
    },
    {
      "id": 25,
      "src": 8,
      "dst": 5,
      "length": 546.8613702582421
    },
    {
      "id": 26,
      "src": 6,
      "dst": 7,
      "length": 233.0775281483698
    },
    {
      "id": 27,
      "src": 7,
      "dst": 6,
      "length": 233.0775281483698
    },
    {
      "id": 28,
      "src": 9,
      "dst": 17,
      "length": 325.0720000910152
    },
    {
      "id": 29,
      "src": 17,
      "dst": 9,
      "length": 325.0720000910152
    },
    {
      "id": 30,
      "src": 9,
      "dst": 11,
      "length": 82.03035170425309
    },
    {
      "id": 31,
      "src": 11,
      "dst": 9,
      "length": 82.03035170425309
    },
    {
      "id": 32,
      "src": 10,
      "dst": 11,
      "length": 27.87704634020835
    },
    {
      "id": 33,
      "src": 11,
      "dst": 10,
      "length": 27.87704634020835
    },
    {
      "id": 34,
      "src": 11,
      "dst": 18,
      "length": 378.2724731274459
    },
    {
      "id": 35,
      "src": 18,
      "dst": 11,
      "length": 378.2724731274459
    },
    {
      "id": 36,
      "src": 12,
      "dst": 13,
      "length": 743.4071200946746
    },
    {
      "id": 37,
      "src": 13,
      "dst": 12,
      "length": 743.4071200946746
    },
    {
      "id": 38,
      "src": 13,
      "dst": 14,
      "length": 418.5080080999496
    },
    {
      "id": 39,
      "src": 14,
      "dst": 13,
      "length": 418.5080080999496
    },
    {
      "id": 40,
      "src": 14,
      "dst": 15,
      "length": 150.1652468643198
    },
    {
      "id": 41,
      "src": 15,
      "dst": 14,
      "length": 150.1652468643198
    },
    {
      "id": 42,
      "src": 14,
      "dst": 17,
      "length": 628.0712841529555
    },
    {
      "id": 43,
      "src": 17,
      "dst": 14,
      "length": 628.0712841529555
    },
    {
      "id": 44,
      "src": 15,
      "dst": 16,
      "length": 755.0357670265992
    },
    {
      "id": 45,
      "src": 16,
      "dst": 15,
      "length": 755.0357670265992
    },
    {
      "id": 46,
      "src": 16,
      "dst": 17,
      "length": 477.4605770094612
    },
    {
      "id": 47,
      "src": 17,
      "dst": 16,
      "length": 477.4605770094612
    },
    {
      "id": 48,
      "src": 16,
      "dst": 19,
      "length": 1187.999858185761
    },
    {
      "id": 49,
      "src": 19,
      "dst": 16,
      "length": 1187.999858185761
    },
    {
      "id": 50,
      "src": 17,
      "dst": 18,
      "length": 335.4884708932951
    },
    {
      "id": 51,
      "src": 18,
      "dst": 17,
      "length": 335.4884708932951
    },
    {
      "id": 52,
      "src": 18,
      "dst": 19,
      "length": 982.8418925334275
    },
    {
      "id": 53,
      "src": 19,
      "dst": 18,
      "length": 982.8418925334275
    }
  ]
}
