=== Kayres21/optical-mb-sim-go/files/networks/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Network Schema",
  "type": "object",
  "properties": {
    "alias": { "type": "string" },
    "name": { "type": "string" },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" }
        },
        "required": ["id"]
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "src": { "type": "integer" },
          "dst": { "type": "integer" },
          "length": { "type": "number" }
        },
        "required": ["id", "src", "dst", "length"]
      }
    }
  },
  "required": ["alias", "name", "nodes", "links"]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_76_OPTUNETSWEDEN.json
{
  "alias": "OPTUNETSWEDEN",
  "name": "TOP_76_OPTUNETSWEDEN",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    },
    {
      "id": 22
    },
    {
      "id": 23
    },
    {
      "id": 24
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 4,
      "length": 190.0960808400053
    },
    {
      "id": 1,
      "src": 4,
      "dst": 0,
      "length": 190.0960808400053
    },
    {
      "id": 2,
      "src": 0,
      "dst": 6,
      "length": 86.74341799687855
    },
    {
      "id": 3,
      "src": 6,
      "dst": 0,
      "length": 86.74341799687855
    },
    {
      "id": 4,
      "src": 0,
      "dst": 7,
      "length": 100.2746698658031
    },
    {
      "id": 5,
      "src": 7,
      "dst": 0,
      "length": 100.2746698658031
    },
    {
      "id": 6,
      "src": 1,
      "dst": 2,
      "length": 188.4095708659947
    },
    {
      "id": 7,
      "src": 2,
      "dst": 1,
      "length": 188.4095708659947
    },
    {
      "id": 8,
      "src": 1,
      "dst": 6,
      "length": 137.3740662255246
    },
    {
      "id": 9,
      "src": 6,
      "dst": 1,
      "length": 137.3740662255246
    },
    {
      "id": 10,
      "src": 1,
      "dst": 7,
      "length": 137.4396981416263
    },
    {
      "id": 11,
      "src": 7,
      "dst": 1,
      "length": 137.4396981416263
    },
    {
      "id": 12,
      "src": 2,
      "dst": 23,
      "length": 203.0177338605977
    },
    {
      "id": 13,
      "src": 23,
      "dst": 2,
      "length": 203.0177338605977
    },
    {
      "id": 14,
      "src": 2,
      "dst": 3,
      "length": 145.9610522942691
    },
    {
      "id": 15,
      "src": 3,
      "dst": 2,
      "length": 145.9610522942691
    },
    {
      "id": 16,
      "src": 2,
      "dst": 17,
      "length": 1253.714379773383
    },
    {
      "id": 17,
      "src": 17,
      "dst": 2,
      "length": 1253.714379773383
    },
    {
      "id": 18,
      "src": 3,
      "dst": 7,
      "length": 210.694581270405
    },
    {
      "id": 19,
      "src": 7,
      "dst": 3,
      "length": 210.694581270405
    },
    {
      "id": 20,
      "src": 4,
      "dst": 10,
      "length": 164.5478734830161
    },
    {
      "id": 21,
      "src": 10,
      "dst": 4,
      "length": 164.5478734830161
    },
    {
      "id": 22,
      "src": 5,
      "dst": 16,
      "length": 260.5348643627447
    },
    {
      "id": 23,
      "src": 16,
      "dst": 5,
      "length": 260.5348643627447
    },
    {
      "id": 24,
      "src": 5,
      "dst": 8,
      "length": 166.7174780120039
    },
    {
      "id": 25,
      "src": 8,
      "dst": 5,
      "length": 166.7174780120039
    },
    {
      "id": 26,
      "src": 8,
      "dst": 9,
      "length": 163.7588213038351
    },
    {
      "id": 27,
      "src": 9,
      "dst": 8,
      "length": 163.7588213038351
    },
    {
      "id": 28,
      "src": 9,
      "dst": 10,
      "length": 245.0906239697914
    },
    {
      "id": 29,
      "src": 10,
      "dst": 9,
      "length": 245.0906239697914
    },
    {
      "id": 30,
      "src": 9,
      "dst": 13,
      "length": 145.3156585583322
    },
    {
      "id": 31,
      "src": 13,
      "dst": 9,
      "length": 145.3156585583322
    },
    {
      "id": 32,
      "src": 10,
      "dst": 15,
      "length": 24.6185530101705
    },
    {
      "id": 33,
      "src": 15,
      "dst": 10,
      "length": 24.6185530101705
    },
    {
      "id": 34,
      "src": 11,
      "dst": 12,
      "length": 108.6370977105624
    },
    {
      "id": 35,
      "src": 12,
      "dst": 11,
      "length": 108.6370977105624
    },
    {
      "id": 36,
      "src": 11,
      "dst": 15,
      "length": 129.1553528994795
    },
    {
      "id": 37,
      "src": 15,
      "dst": 11,
      "length": 129.1553528994795
    },
    {
      "id": 38,
      "src": 12,
      "dst": 13,
      "length": 125.2771429335356
    },
    {
      "id": 39,
      "src": 13,
      "dst": 12,
      "length": 125.2771429335356
    },
    {
      "id": 40,
      "src": 14,
      "dst": 16,
      "length": 282.8790813503142
    },
    {
      "id": 41,
      "src": 16,
      "dst": 14,
      "length": 282.8790813503142
    },
    {
      "id": 42,
      "src": 16,
      "dst": 17,
      "length": 1154.573279465749
    },
    {
      "id": 43,
      "src": 17,
      "dst": 16,
      "length": 1154.573279465749
    },
    {
      "id": 44,
      "src": 16,
      "dst": 24,
      "length": 94.59605471963164
    },
    {
      "id": 45,
      "src": 24,
      "dst": 16,
      "length": 94.59605471963164
    },
    {
      "id": 46,
      "src": 18,
      "dst": 19,
      "length": 399.6140407572479
    },
    {
      "id": 47,
      "src": 19,
      "dst": 18,
      "length": 399.6140407572479
    },
    {
      "id": 48,
      "src": 19,
      "dst": 20,
      "length": 322.4443218961811
    },
    {
      "id": 49,
      "src": 20,
      "dst": 19,
      "length": 322.4443218961811
    },
    {
      "id": 50,
      "src": 20,
      "dst": 21,
      "length": 327.1913618719075
    },
    {
      "id": 51,
      "src": 21,
      "dst": 20,
      "length": 327.1913618719075
    },
    {
      "id": 52,
      "src": 21,
      "dst": 22,
      "length": 286.6426397341182
    },
    {
      "id": 53,
      "src": 22,
      "dst": 21,
      "length": 286.6426397341182
    },
    {
      "id": 54,
      "src": 22,
      "dst": 23,
      "length": 143.1556159924878
    },
    {
      "id": 55,
      "src": 23,
      "dst": 22,
      "length": 143.1556159924878
    },
    {
      "id": 56,
      "src": 22,
      "dst": 24,
      "length": 142.339911379905
    },
    {
      "id": 57,
      "src": 24,
      "dst": 22,
      "length": 142.339911379905
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_82_POLSKA.json
{
  "alias": "POLSKA",
  "name": "TOP_82_POLSKA",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 10,
      "length": 410.7744042567559
    },
    {
      "id": 1,
      "src": 10,
      "dst": 0,
      "length": 410.7744042567559
    },
    {
      "id": 2,
      "src": 0,
      "dst": 2,
      "length": 243.9034925586963
    },
    {
      "id": 3,
      "src": 2,
      "dst": 0,
      "length": 243.9034925586963
    },
    {
      "id": 4,
      "src": 0,
      "dst": 5,
      "length": 481.1108566271961
    },
    {
      "id": 5,
      "src": 5,
      "dst": 0,
      "length": 481.1108566271961
    },
    {
      "id": 6,
      "src": 1,
      "dst": 2,
      "length": 255.5770705699139
    },
    {
      "id": 7,
      "src": 2,
      "dst": 1,
      "length": 255.5770705699139
    },
    {
      "id": 8,
      "src": 1,
      "dst": 7,
      "length": 161.1319834866405
    },
    {
      "id": 9,
      "src": 7,
      "dst": 1,
      "length": 161.1319834866405
    },
    {
      "id": 10,
      "src": 1,
      "dst": 10,
      "length": 347.7170275587544
    },
    {
      "id": 11,
      "src": 10,
      "dst": 1,
      "length": 347.7170275587544
    },
    {
      "id": 12,
      "src": 2,
      "dst": 9,
      "length": 206.5017098295303
    },
    {
      "id": 13,
      "src": 9,
      "dst": 2,
      "length": 206.5017098295303
    },
    {
      "id": 14,
      "src": 3,
      "dst": 4,
      "length": 118.009331406665
    },
    {
      "id": 15,
      "src": 4,
      "dst": 3,
      "length": 118.009331406665
    },
    {
      "id": 16,
      "src": 3,
      "dst": 6,
      "length": 241.8510106704026
    },
    {
      "id": 17,
      "src": 6,
      "dst": 3,
      "length": 241.8510106704026
    },
    {
      "id": 18,
      "src": 3,
      "dst": 11,
      "length": 241.0147228136016
    },
    {
      "id": 19,
      "src": 11,
      "dst": 3,
      "length": 241.0147228136016
    },
    {
      "id": 20,
      "src": 4,
      "dst": 8,
      "length": 225.1379758967965
    },
    {
      "id": 21,
      "src": 8,
      "dst": 4,
      "length": 225.1379758967965
    },
    {
      "id": 22,
      "src": 4,
      "dst": 10,
      "length": 387.8574867354514
    },
    {
      "id": 23,
      "src": 10,
      "dst": 4,
      "length": 387.8574867354514
    },
    {
      "id": 24,
      "src": 5,
      "dst": 8,
      "length": 531.804038576357
    },
    {
      "id": 25,
      "src": 8,
      "dst": 5,
      "length": 531.804038576357
    },
    {
      "id": 26,
      "src": 5,
      "dst": 10,
      "length": 260.1554864729655
    },
    {
      "id": 27,
      "src": 10,
      "dst": 5,
      "length": 260.1554864729655
    },
    {
      "id": 28,
      "src": 6,
      "dst": 10,
      "length": 184.4117882015071
    },
    {
      "id": 29,
      "src": 10,
      "dst": 6,
      "length": 184.4117882015071
    },
    {
      "id": 30,
      "src": 6,
      "dst": 11,
      "length": 278.712944604
    },
    {
      "id": 31,
      "src": 11,
      "dst": 6,
      "length": 278.712944604
    },
    {
      "id": 32,
      "src": 7,
      "dst": 9,
      "length": 285.227139412663
    },
    {
      "id": 33,
      "src": 9,
      "dst": 7,
      "length": 285.227139412663
    },
    {
      "id": 34,
      "src": 7,
      "dst": 11,
      "length": 217.0757821935017
    },
    {
      "id": 35,
      "src": 11,
      "dst": 7,
      "length": 217.0757821935017
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_96_SAGO.json
{
  "alias": "SAGO",
  "name": "TOP_96_SAGO",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 1,
      "length": 112.9130335236984
    },
    {
      "id": 1,
      "src": 1,
      "dst": 0,
      "length": 112.9130335236984
    },
    {
      "id": 2,
      "src": 0,
      "dst": 4,
      "length": 128.6622981191926
    },
    {
      "id": 3,
      "src": 4,
      "dst": 0,
      "length": 128.6622981191926
    },
    {
      "id": 4,
      "src": 1,
      "dst": 16,
      "length": 93.14768168607968
    },
    {
      "id": 5,
      "src": 16,
      "dst": 1,
      "length": 93.14768168607968
    },
    {
      "id": 6,
      "src": 2,
      "dst": 3,
      "length": 90.14377938900955
    },
    {
      "id": 7,
      "src": 3,
      "dst": 2,
      "length": 90.14377938900955
    },
    {
      "id": 8,
      "src": 2,
      "dst": 5,
      "length": 111.4326474233612
    },
    {
      "id": 9,
      "src": 5,
      "dst": 2,
      "length": 111.4326474233612
    },
    {
      "id": 10,
      "src": 3,
      "dst": 17,
      "length": 123.502526239912
    },
    {
      "id": 11,
      "src": 17,
      "dst": 3,
      "length": 123.502526239912
    },
    {
      "id": 12,
      "src": 4,
      "dst": 7,
      "length": 100.9743372348429
    },
    {
      "id": 13,
      "src": 7,
      "dst": 4,
      "length": 100.9743372348429
    },
    {
      "id": 14,
      "src": 6,
      "dst": 7,
      "length": 58.85702770663077
    },
    {
      "id": 15,
      "src": 7,
      "dst": 6,
      "length": 58.85702770663077
    },
    {
      "id": 16,
      "src": 8,
      "dst": 9,
      "length": 107.7012067809803
    },
    {
      "id": 17,
      "src": 9,
      "dst": 8,
      "length": 107.7012067809803
    },
    {
      "id": 18,
      "src": 8,
      "dst": 11,
      "length": 100.7797542631112
    },
    {
      "id": 19,
      "src": 11,
      "dst": 8,
      "length": 100.7797542631112
    },
    {
      "id": 20,
      "src": 10,
      "dst": 11,
      "length": 142.935071154233
    },
    {
      "id": 21,
      "src": 11,
      "dst": 10,
      "length": 142.935071154233
    },
    {
      "id": 22,
      "src": 10,
      "dst": 13,
      "length": 112.280376164828
    },
    {
      "id": 23,
      "src": 13,
      "dst": 10,
      "length": 112.280376164828
    },
    {
      "id": 24,
      "src": 12,
      "dst": 13,
      "length": 132.6014600386424
    },
    {
      "id": 25,
      "src": 13,
      "dst": 12,
      "length": 132.6014600386424
    },
    {
      "id": 26,
      "src": 12,
      "dst": 15,
      "length": 114.1091942451913
    },
    {
      "id": 27,
      "src": 15,
      "dst": 12,
      "length": 114.1091942451913
    },
    {
      "id": 28,
      "src": 14,
      "dst": 17,
      "length": 120.972544952087
    },
    {
      "id": 29,
      "src": 17,
      "dst": 14,
      "length": 120.972544952087
    },
    {
      "id": 30,
      "src": 14,
      "dst": 15,
      "length": 89.08495741337417
    },
    {
      "id": 31,
      "src": 15,
      "dst": 14,
      "length": 89.08495741337417
    },
    {
      "id": 32,
      "src": 16,
      "dst": 17,
      "length": 104.6670832176189
    },
    {
      "id": 33,
      "src": 17,
      "dst": 16,
      "length": 104.6670832176189
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_88_RENATER.json
{
  "alias": "RENATER",
  "name": "TOP_88_RENATER",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    },
    {
      "id": 22
    },
    {
      "id": 23
    },
    {
      "id": 24
    },
    {
      "id": 25
    },
    {
      "id": 26
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 1,
      "length": 204.838876809736
    },
    {
      "id": 1,
      "src": 1,
      "dst": 0,
      "length": 204.838876809736
    },
    {
      "id": 2,
      "src": 0,
      "dst": 2,
      "length": 307.135115440902
    },
    {
      "id": 3,
      "src": 2,
      "dst": 0,
      "length": 307.135115440902
    },
    {
      "id": 4,
      "src": 1,
      "dst": 2,
      "length": 108.383373166042
    },
    {
      "id": 5,
      "src": 2,
      "dst": 1,
      "length": 108.383373166042
    },
    {
      "id": 6,
      "src": 2,
      "dst": 3,
      "length": 198.576777330228
    },
    {
      "id": 7,
      "src": 3,
      "dst": 2,
      "length": 198.576777330228
    },
    {
      "id": 8,
      "src": 2,
      "dst": 8,
      "length": 590.03745510248
    },
    {
      "id": 9,
      "src": 8,
      "dst": 2,
      "length": 590.03745510248
    },
    {
      "id": 10,
      "src": 2,
      "dst": 26,
      "length": 165.864322588038
    },
    {
      "id": 11,
      "src": 26,
      "dst": 2,
      "length": 165.864322588038
    },
    {
      "id": 12,
      "src": 2,
      "dst": 16,
      "length": 440.190149106402
    },
    {
      "id": 13,
      "src": 16,
      "dst": 2,
      "length": 440.190149106402
    },
    {
      "id": 14,
      "src": 2,
      "dst": 22,
      "length": 165.227218096153
    },
    {
      "id": 15,
      "src": 22,
      "dst": 2,
      "length": 165.227218096153
    },
    {
      "id": 16,
      "src": 3,
      "dst": 4,
      "length": 253.625186338797
    },
    {
      "id": 17,
      "src": 4,
      "dst": 3,
      "length": 253.625186338797
    },
    {
      "id": 18,
      "src": 4,
      "dst": 5,
      "length": 173.695286591785
    },
    {
      "id": 19,
      "src": 5,
      "dst": 4,
      "length": 173.695286591785
    },
    {
      "id": 20,
      "src": 5,
      "dst": 6,
      "length": 296.118414821324
    },
    {
      "id": 21,
      "src": 6,
      "dst": 5,
      "length": 296.118414821324
    },
    {
      "id": 22,
      "src": 6,
      "dst": 7,
      "length": 112.088429271704
    },
    {
      "id": 23,
      "src": 7,
      "dst": 6,
      "length": 112.088429271704
    },
    {
      "id": 24,
      "src": 7,
      "dst": 8,
      "length": 261.929176971129
    },
    {
      "id": 25,
      "src": 8,
      "dst": 7,
      "length": 261.929176971129
    },
    {
      "id": 26,
      "src": 8,
      "dst": 9,
      "length": 142.198268208719
    },
    {
      "id": 27,
      "src": 9,
      "dst": 8,
      "length": 142.198268208719
    },
    {
      "id": 28,
      "src": 8,
      "dst": 12,
      "length": 375.518825446673
    },
    {
      "id": 29,
      "src": 12,
      "dst": 8,
      "length": 375.518825446673
    },
    {
      "id": 30,
      "src": 8,
      "dst": 18,
      "length": 203.64194208922
    },
    {
      "id": 31,
      "src": 18,
      "dst": 8,
      "length": 203.64194208922
    },
    {
      "id": 32,
      "src": 9,
      "dst": 10,
      "length": 307.86609911131
    },
    {
      "id": 33,
      "src": 10,
      "dst": 9,
      "length": 307.86609911131
    },
    {
      "id": 34,
      "src": 10,
      "dst": 11,
      "length": 239.401579550886
    },
    {
      "id": 35,
      "src": 11,
      "dst": 10,
      "length": 239.401579550886
    },
    {
      "id": 36,
      "src": 11,
      "dst": 12,
      "length": 188.277938375392
    },
    {
      "id": 37,
      "src": 12,
      "dst": 11,
      "length": 188.277938375392
    },
    {
      "id": 38,
      "src": 12,
      "dst": 13,
      "length": 293.764953427563
    },
    {
      "id": 39,
      "src": 13,
      "dst": 12,
      "length": 293.764953427563
    },
    {
      "id": 40,
      "src": 13,
      "dst": 14,
      "length": 225.461210053238
    },
    {
      "id": 41,
      "src": 14,
      "dst": 13,
      "length": 225.461210053238
    },
    {
      "id": 42,
      "src": 14,
      "dst": 15,
      "length": 259.015552293153
    },
    {
      "id": 43,
      "src": 15,
      "dst": 14,
      "length": 259.015552293153
    },
    {
      "id": 44,
      "src": 13,
      "dst": 15,
      "length": 317.940061078348
    },
    {
      "id": 45,
      "src": 15,
      "dst": 13,
      "length": 317.940061078348
    },
    {
      "id": 46,
      "src": 15,
      "dst": 16,
      "length": 309.21999360776
    },
    {
      "id": 47,
      "src": 16,
      "dst": 15,
      "length": 309.21999360776
    },
    {
      "id": 48,
      "src": 16,
      "dst": 17,
      "length": 163.754427729405
    },
    {
      "id": 49,
      "src": 17,
      "dst": 16,
      "length": 163.754427729405
    },
    {
      "id": 50,
      "src": 16,
      "dst": 26,
      "length": 283.178847854488
    },
    {
      "id": 51,
      "src": 26,
      "dst": 16,
      "length": 283.178847854488
    },
    {
      "id": 52,
      "src": 16,
      "dst": 19,
      "length": 240.709994185667
    },
    {
      "id": 53,
      "src": 19,
      "dst": 16,
      "length": 240.709994185667
    },
    {
      "id": 54,
      "src": 17,
      "dst": 18,
      "length": 211.529713997921
    },
    {
      "id": 55,
      "src": 18,
      "dst": 17,
      "length": 211.529713997921
    },
    {
      "id": 56,
      "src": 19,
      "dst": 23,
      "length": 121.043523684447
    },
    {
      "id": 57,
      "src": 23,
      "dst": 19,
      "length": 121.043523684447
    },
    {
      "id": 58,
      "src": 19,
      "dst": 20,
      "length": 149.565910700829
    },
    {
      "id": 59,
      "src": 20,
      "dst": 19,
      "length": 149.565910700829
    },
    {
      "id": 60,
      "src": 20,
      "dst": 21,
      "length": 229.987194956398
    },
    {
      "id": 61,
      "src": 21,
      "dst": 20,
      "length": 229.987194956398
    },
    {
      "id": 62,
      "src": 21,
      "dst": 22,
      "length": 164.277160609869
    },
    {
      "id": 63,
      "src": 22,
      "dst": 21,
      "length": 164.277160609869
    },
    {
      "id": 64,
      "src": 23,
      "dst": 24,
      "length": 122.31295889346
    },
    {
      "id": 65,
      "src": 24,
      "dst": 23,
      "length": 122.31295889346
    },
    {
      "id": 66,
      "src": 24,
      "dst": 25,
      "length": 116.851397341314
    },
    {
      "id": 67,
      "src": 25,
      "dst": 24,
      "length": 116.851397341314
    },
    {
      "id": 68,
      "src": 25,
      "dst": 26,
      "length": 161.540100224565
    },
    {
      "id": 69,
      "src": 26,
      "dst": 25,
      "length": 161.540100224565
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_34_GBLNET.json
{
  "alias": "GBLNET",
  "name": "TOP_34_GBLNET",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 5,
      "length": 521.6095788482335
    },
    {
      "id": 1,
      "src": 5,
      "dst": 0,
      "length": 521.6095788482335
    },
    {
      "id": 2,
      "src": 1,
      "dst": 5,
      "length": 535.6163051270169
    },
    {
      "id": 3,
      "src": 5,
      "dst": 1,
      "length": 535.6163051270169
    },
    {
      "id": 4,
      "src": 2,
      "dst": 3,
      "length": 1032.15219238748
    },
    {
      "id": 5,
      "src": 3,
      "dst": 2,
      "length": 1032.15219238748
    },
    {
      "id": 6,
      "src": 2,
      "dst": 5,
      "length": 1500.0
    },
    {
      "id": 7,
      "src": 5,
      "dst": 2,
      "length": 1500.0
    },
    {
      "id": 8,
      "src": 3,
      "dst": 4,
      "length": 949.8667213173954
    },
    {
      "id": 9,
      "src": 4,
      "dst": 3,
      "length": 949.8667213173954
    },
    {
      "id": 10,
      "src": 5,
      "dst": 6,
      "length": 545.2339470871901
    },
    {
      "id": 11,
      "src": 6,
      "dst": 5,
      "length": 545.2339470871901
    },
    {
      "id": 12,
      "src": 5,
      "dst": 7,
      "length": 645.6357804808555
    },
    {
      "id": 13,
      "src": 7,
      "dst": 5,
      "length": 645.6357804808555
    }
  ]
}

=== Kayres21/optical-mb-sim-go/files/networks/TOP_84_PSINET.json
{
  "alias": "PSINET",
  "name": "TOP_84_PSINET",
  "nodes": [
    {
      "id": 0
    },
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6
    },
    {
      "id": 7
    },
    {
      "id": 8
    },
    {
      "id": 9
    },
    {
      "id": 10
    },
    {
      "id": 11
    },
    {
      "id": 12
    },
    {
      "id": 13
    },
    {
      "id": 14
    },
    {
      "id": 15
    },
    {
      "id": 16
    },
    {
      "id": 17
    },
    {
      "id": 18
    },
    {
      "id": 19
    },
    {
      "id": 20
    },
    {
      "id": 21
    },
    {
      "id": 22
    },
    {
      "id": 23
    }
  ],
  "links": [
    {
      "id": 0,
      "src": 0,
      "dst": 3,
      "length": 128.3933603139128
    },
    {
      "id": 1,
      "src": 3,
      "dst": 0,
      "length": 128.3933603139128
    },
    {
      "id": 2,
      "src": 1,
      "dst": 2,
      "length": 1500.0
    },
    {
      "id": 3,
      "src": 2,
      "dst": 1,
      "length": 1500.0
    },
    {
      "id": 4,
      "src": 1,
      "dst": 3,
      "length": 1500.0
    },
    {
      "id": 5,
      "src": 3,
      "dst": 1,
      "length": 1500.0
    },
    {
      "id": 6,
      "src": 1,
      "dst": 4,
      "length": 1324.067201764712
    },
    {
      "id": 7,
      "src": 4,
      "dst": 1,
      "length": 1324.067201764712
    },
    {
      "id": 8,
      "src": 2,
      "dst": 3,
      "length": 509.8435626304135
    },
    {
      "id": 9,
      "src": 3,
      "dst": 2,
      "length": 509.8435626304135
    },
    {
      "id": 10,
      "src": 2,
      "dst": 15,
      "length": 627.5025611615271
    },
    {
      "id": 11,
      "src": 15,
      "dst": 2,
      "length": 627.5025611615271
    },
    {
      "id": 12,
      "src": 4,
      "dst": 5,
      "length": 85.61340860642284
    },
    {
      "id": 13,
      "src": 5,
      "dst": 4,
      "length": 85.61340860642284
    },
    {
      "id": 14,
      "src": 5,
      "dst": 8,
      "length": 862.4466435705526
    },
    {
      "id": 15,
      "src": 8,
      "dst": 5,
      "length": 862.4466435705526
    },
    {
      "id": 16,
      "src": 6,
      "dst": 12,
      "length": 521.0951719218651
    },
    {
      "id": 17,
      "src": 12,
      "dst": 6,
      "length": 521.0951719218651
    },
    {
      "id": 18,
      "src": 6,
      "dst": 7,
      "length": 1280.659967318184
    },
    {
      "id": 19,
      "src": 7,
      "dst": 6,
      "length": 1280.659967318184
    },
    {
      "id": 20,
      "src": 7,
      "dst": 23,
      "length": 1500.0
    },
    {
      "id": 21,
      "src": 23,
      "dst": 7,
      "length": 1500.0
    },
    {
      "id": 22,
      "src": 8,
      "dst": 9,
      "length": 1023.08605411639
    },
    {
      "id": 23,
      "src": 9,
      "dst": 8,
      "length": 1023.08605411639
    },
    {
      "id": 24,
      "src": 9,
      "dst": 13,
      "length": 182.2082908548479
    },
    {
      "id": 25,
      "src": 13,
      "dst": 9,
      "length": 182.2082908548479
    },
    {
      "id": 26,
      "src": 10,
      "dst": 12,
      "length": 459.728758316418
    },
    {
      "id": 27,
      "src": 12,
      "dst": 10,
      "length": 459.728758316418
    },
    {
      "id": 28,
      "src": 11,
      "dst": 12,
      "length": 1181.526912522182
    },
    {
      "id": 29,
      "src": 12,
      "dst": 11,
      "length": 1181.526912522182
    },
    {
      "id": 30,
      "src": 12,
      "dst": 13,
      "length": 20.83436718327859
    },
    {
      "id": 31,
      "src": 13,
      "dst": 12,
      "length": 20.83436718327859
    },
    {
      "id": 32,
      "src": 14,
      "dst": 19,
      "length": 2102.128051806963
    },
    {
      "id": 33,
      "src": 19,
      "dst": 14,
      "length": 2102.128051806963
    },
    {
      "id": 34,
      "src": 14,
      "dst": 22,
      "length": 1095.95956804919
    },
    {
      "id": 35,
      "src": 22,
      "dst": 14,
      "length": 1095.95956804919
    },
    {
      "id": 36,
      "src": 14,
      "dst": 15,
      "length": 580.7625411994072
    },
    {
      "id": 37,
      "src": 15,
      "dst": 14,
      "length": 580.7625411994072
    },
    {
      "id": 38,
      "src": 16,
      "dst": 17,
      "length": 92.77121696685674
    },
    {
      "id": 39,
      "src": 17,
      "dst": 16,
      "length": 92.77121696685674
    },
    {
      "id": 40,
      "src": 16,
      "dst": 18,
      "length": 838.7553033988663
    },
    {
      "id": 41,
      "src": 18,
      "dst": 16,
      "length": 838.7553033988663
    },
    {
      "id": 42,
      "src": 18,
      "dst": 19,
      "length": 861.3692628497527
    },
    {
      "id": 43,
      "src": 19,
      "dst": 18,
      "length": 861.3692628497527
    },
    {
      "id": 44,
      "src": 20,
      "dst": 23,
      "length": 354.0915074929874
    },
    {
      "id": 45,
      "src": 23,
      "dst": 20,
      "length": 354.0915074929874
    },
    {
      "id": 46,
      "src": 21,
      "dst": 22,
      "length": 72.02261095132675
    },
    {
      "id": 47,
      "src": 22,
      "dst": 21,
      "length": 72.02261095132675
    },
    {
      "id": 48,
      "src": 22,
      "dst": 23,
      "length": 544.4600499700148
    },
    {
      "id": 49,
      "src": 23,
      "dst": 22,
      "length": 544.4600499700148
    }
  ]
}
